### PR TITLE
add leaflet extension

### PR DESCRIPTION
**Pull request by gnijuohz**
Add leaflet extension.

### CODE REVIEW

**Comment by Ovilia** [comment]
Do you have any document or readme on your plugin?

**Comment by gnijuohz** [comment]
@Ovilia There is a [test html](https://github.com/gnijuohz/echarts/blob/leaflet-extension/test/leaflet.html) file in the test folder. I'll add a documentation like [bmap](https://github.com/ecomfe/echarts/tree/master/extension/bmap).

**Comment by Justineo** [comment]
I think you'd better create a separate repo for the extension and make ECharts a dependency for your project, rather than fork the official repo and put your extension inside it. Moreover, a clear documentation about how to install (from package managers like NPM) and include your extension is also the proper way to release an extension.

**Comment by Justineo** [comment]
BMap is a built-in extension for ECharts and maintained with the official repo. I recommend you to check out independent extensions like [ECharts wordcloud extension](https://github.com/ecomfe/echarts-wordcloud) and [ECharts graph modularity extension](https://github.com/ecomfe/echarts-graph-modularity).

**Comment by gnijuohz** [comment]
Thanks @Justineo I'll do that. I'll ping again when it's all done. Thanks for your time :)

**Comment by Justineo** [comment]
Thanks for your contribution. 👍 👍

**Comment by Ovilia** [comment]
@gnijuohz I'll add this repo to http://echarts.baidu.com/download-extension.html later.
Thanks for your contribution.

**Comment by gnijuohz** [comment]
@Ovilia Thanks for your time 👍

**Pull request merged**
